"""empty message

Revision ID: bf33269aa376
Revises: e2e17083447a
Create Date: 2021-09-28 23:30:30.094581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf33269aa376'
down_revision = 'e2e17083447a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracking_outgoing_request_best_proxies_request_datetime', table_name='tracking_outgoing_request_best_proxies')
    op.drop_index('ix_tracking_outgoing_request_best_proxies_request_method', table_name='tracking_outgoing_request_best_proxies')
    op.drop_index('ix_tracking_outgoing_request_best_proxies_request_url', table_name='tracking_outgoing_request_best_proxies')
    op.drop_index('ix_tracking_outgoing_request_best_proxies_response_datetime', table_name='tracking_outgoing_request_best_proxies')
    op.drop_index('ix_tracking_outgoing_request_best_proxies_response_status_code', table_name='tracking_outgoing_request_best_proxies')
    op.drop_table('tracking_outgoing_request_best_proxies')
    op.drop_index('ix_tracking_outgoing_request_ip_service_request_datetime', table_name='tracking_outgoing_request_ip_service')
    op.drop_index('ix_tracking_outgoing_request_ip_service_request_method', table_name='tracking_outgoing_request_ip_service')
    op.drop_index('ix_tracking_outgoing_request_ip_service_request_url', table_name='tracking_outgoing_request_ip_service')
    op.drop_index('ix_tracking_outgoing_request_ip_service_response_datetime', table_name='tracking_outgoing_request_ip_service')
    op.drop_index('ix_tracking_outgoing_request_ip_service_response_status_code', table_name='tracking_outgoing_request_ip_service')
    op.drop_table('tracking_outgoing_request_ip_service')
    op.drop_index('ix_proxy_deleted_at', table_name='proxy')
    op.drop_column('proxy', 'deleted_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxy', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_proxy_deleted_at', 'proxy', ['deleted_at'], unique=False)
    op.create_table('tracking_outgoing_request_ip_service',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('request_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_body', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('response_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_body', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('elapsed_time', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('exception', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_tracking_outgoing_request_ip_service')
    )
    op.create_index('ix_tracking_outgoing_request_ip_service_response_status_code', 'tracking_outgoing_request_ip_service', ['response_status_code'], unique=False)
    op.create_index('ix_tracking_outgoing_request_ip_service_response_datetime', 'tracking_outgoing_request_ip_service', ['response_datetime'], unique=False)
    op.create_index('ix_tracking_outgoing_request_ip_service_request_url', 'tracking_outgoing_request_ip_service', ['request_url'], unique=False)
    op.create_index('ix_tracking_outgoing_request_ip_service_request_method', 'tracking_outgoing_request_ip_service', ['request_method'], unique=False)
    op.create_index('ix_tracking_outgoing_request_ip_service_request_datetime', 'tracking_outgoing_request_ip_service', ['request_datetime'], unique=False)
    op.create_table('tracking_outgoing_request_best_proxies',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('request_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('request_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_method', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_body', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('response_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('response_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_body', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('elapsed_time', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('exception', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_tracking_outgoing_request_best_proxies')
    )
    op.create_index('ix_tracking_outgoing_request_best_proxies_response_status_code', 'tracking_outgoing_request_best_proxies', ['response_status_code'], unique=False)
    op.create_index('ix_tracking_outgoing_request_best_proxies_response_datetime', 'tracking_outgoing_request_best_proxies', ['response_datetime'], unique=False)
    op.create_index('ix_tracking_outgoing_request_best_proxies_request_url', 'tracking_outgoing_request_best_proxies', ['request_url'], unique=False)
    op.create_index('ix_tracking_outgoing_request_best_proxies_request_method', 'tracking_outgoing_request_best_proxies', ['request_method'], unique=False)
    op.create_index('ix_tracking_outgoing_request_best_proxies_request_datetime', 'tracking_outgoing_request_best_proxies', ['request_datetime'], unique=False)
    # ### end Alembic commands ###
