"""empty message

Revision ID: e7e01ff1f6c7
Revises: 76d6c7534cf1
Create Date: 2021-09-06 12:22:43.266184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7e01ff1f6c7'
down_revision = '76d6c7534cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_outgoing_request_ip_service',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_url', sa.Unicode(), nullable=False),
    sa.Column('request_method', sa.Unicode(), nullable=False),
    sa.Column('request_headers', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('request_body', sa.LargeBinary(), nullable=True),
    sa.Column('response_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('response_body', sa.LargeBinary(), nullable=True),
    sa.Column('elapsed_time', sa.Interval(), nullable=True),
    sa.Column('exception', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracking_outgoing_request_ip_service'))
    )
    op.create_index(op.f('ix_tracking_outgoing_request_ip_service_request_datetime'), 'tracking_outgoing_request_ip_service', ['request_datetime'], unique=False)
    op.create_index(op.f('ix_tracking_outgoing_request_ip_service_request_method'), 'tracking_outgoing_request_ip_service', ['request_method'], unique=False)
    op.create_index(op.f('ix_tracking_outgoing_request_ip_service_request_url'), 'tracking_outgoing_request_ip_service', ['request_url'], unique=False)
    op.create_index(op.f('ix_tracking_outgoing_request_ip_service_response_datetime'), 'tracking_outgoing_request_ip_service', ['response_datetime'], unique=False)
    op.create_index(op.f('ix_tracking_outgoing_request_ip_service_response_status_code'), 'tracking_outgoing_request_ip_service', ['response_status_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_outgoing_request_ip_service_response_status_code'), table_name='tracking_outgoing_request_ip_service')
    op.drop_index(op.f('ix_tracking_outgoing_request_ip_service_response_datetime'), table_name='tracking_outgoing_request_ip_service')
    op.drop_index(op.f('ix_tracking_outgoing_request_ip_service_request_url'), table_name='tracking_outgoing_request_ip_service')
    op.drop_index(op.f('ix_tracking_outgoing_request_ip_service_request_method'), table_name='tracking_outgoing_request_ip_service')
    op.drop_index(op.f('ix_tracking_outgoing_request_ip_service_request_datetime'), table_name='tracking_outgoing_request_ip_service')
    op.drop_table('tracking_outgoing_request_ip_service')
    # ### end Alembic commands ###
